# -*- buffer-read-only: t -*-
# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is built by regen/pX.pl.
# Any changes made here will be lost!


package p7;

# use p7 enables perl 5 code to function in a perl 7-ish way as much as possible compared to the version you are running.
# it also is a hint to both tools and the compiler what the level of compatibility is with future versions of the language.

our $VERSION = '0.00001';

BEGIN {
    # This code is a proof of concept provided against 5.30. In order for this code to work on other versions of perl
    # we would need to generate it as part of shipping it to CPAN.
    $] >= 5.030 or die("Perl 5.30 is required to use this module.");
}

sub import {

    ${^WARNING_BITS} = pack( "H*", '55555555555555555555555515000150010154' );

    $^H |= 0x00000602;

    foreach my $f ( qw{say state evalbytes current_sub fc postderef indirect} ) {
        $^H{$f} = 1;
    }
    # alternatively
    # require feature;
    # feature->import(qw{say state evalbytes current_sub fc postderef indirect});

    return;
}

1;

__END__

=head1 NAME

p7

=head1 SYNOPSIS

use p7;

=head1 DESCRIPTION

Description for p7.

=head1 AUTHOR

atoomic

=cut


# ex: set ro:
