name: "Push Notification p7"
on: [push, pull_request]
# add create for tracking tags

# IRC colors: https://modern.ircdocs.horse/formatting.html
# yaml formating: https://www.yaml.info/learn/quote.html

jobs:
  notify-irc:
    runs-on: ubuntu-latest
    # only on main repo
    if: github.repository == 'atoomic/perl'

    env:
      server: ssl.irc.perl.org
      port: 7062
      channel: "#p7-dev"

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: irc push
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'push'
        # && github.ref != 'refs/heads/blead'
        with:
          server: ${{ env.server }}
          port: ${{ env.port }}
          channel: ${{ env.channel }}
          nickname: Push
          message:
            "\x037${{ github.actor }}\x0F pushed to \x033${{ github.event.ref }}\x0F\n\
            ${{ join(github.event.commits.*.message) }}\n\
            ${{ github.event.compare }}\
            "

      - name: irc pull request
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'pull_request'
        with:
          server: ${{ env.server }}
          port: ${{ env.port }}
          channel: ${{ env.channel }}
          nickname: new-PR
          message:
            "\x037${{ github.actor }}\x0F opened PR #${{ github.event.pull_request.number }}\n\
            ${{ github.event.pull_request.title }}\n\
            \x0313${{ github.event.html_url }}\x0F"
